AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "wolfeidau: aws billing partition lambda which detects new files in the CUR hive folder and creates athena partitions"

Parameters:
  Stage:
    Type: String
    Description: The stage where the stack is running in, e.g., dev, prod.
    Default: dev
  Branch:
    Type: String
    Description: The branch the stack was deployed.
    Default: master
  ReportBucketName:
    Description: The name of the bucket you have configured to receive CUR files.
    Type: String
  CurPrefix:
    Type: String
    Description: The prefix for the CUR files in the bucket, this should exclude the leading '/'.
  Commit:
    Type: String
  GlueDatabase:
    Type: String
  GlueTable:
    Type: String
  QueryResultsBucketName:
    Type: String
  AthenaWorkGroupName:
    Type: String
    Description: The name of the Athena workgroup for query execution

Conditions:
  IsDev: !Equals [!Ref Stage, "dev"]
  IsProd: !Equals [!Ref Stage, "prod"]

Globals:
  Function:
    Runtime: provided.al2
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        STAGE: !Ref Stage
        BRANCH: !Ref Branch
        COMMIT: !Ref Commit
        AWS_ACCOUNT_ID: !Ref "AWS::AccountId"
        RAW_EVENT_LOGGING: !If [IsDev, "true", "false"]

Resources:
  ReportS3EventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ReportS3EventRule"
      EventPattern:
        source:
          - "aws.s3"
        "detail-type":
          - "Object Created"
        detail:
          bucket:
            name:
              - !Ref ReportBucketName
          object:
            key:
              - prefix: !Ref CurPrefix
              - suffix: !Sub 01/${ReportBucketName}-Manifest.json
      Targets:
        - Arn: !GetAtt PartitionsFunction.Arn
          InputTransformer:
            InputPathsMap:
                "bucket": "$.detail.bucket.name"
                "key": "$.detail.object.key"
                "etag": "$.detail.object.etag"
                "requester": "$.detail.requester"
            InputTemplate: >
              {
                "bucket": "<bucket>",
                "key": "<key>",
                "etag": "<etag>",
                "requester": "<requester>"
              }
          Id: !Sub "PartitionsFunction-${Stage}-${Branch}"

  PartitionsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PartitionsFunction}"
      RetentionInDays: !If [IsProd, 365, 14]

  PartitionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../dist/partitions-curs-lambda-handler.zip
      Handler: bootstrap
      Environment:
        Variables:
          DATABASE: !Ref GlueDatabase
          TABLE: !Ref GlueTable
          QUERY_BUCKET: !Ref QueryResultsBucketName
          ATHENA_WORKGROUP_NAME: !Ref AthenaWorkGroupName
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: default
        - S3CrudPolicy:
            BucketName: !Ref ReportBucketName
        - S3ReadPolicy:
            BucketName: !Ref QueryResultsBucketName
        - S3WritePolicy:
            BucketName: !Ref QueryResultsBucketName
        - AthenaQueryPolicy:
            WorkGroupName: !Ref AthenaWorkGroupName
        - Version: "2012-10-17"
          Statement:
            # Glue database permissions
            - Effect: Allow
              Action:
                - "glue:GetDatabase"
              Resource:
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${GlueDatabase}"
            # Glue table permissions for partition management
            - Effect: Allow
              Action:
                - "glue:GetTable"
                - "glue:BatchCreatePartition"
              Resource:
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${GlueDatabase}"
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${GlueDatabase}/${GlueTable}"

  PartitionsFunctionS3EventRulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: PartitionsFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ReportS3EventRule.Arn
