AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "wolfeidau: aws billing partition lambda which detects new files in the CUR hive folder and creates athena partitions"

Parameters:
  Stage:
    Type: String
    Description: The stage where the stack is running in, e.g., dev, prod.
    Default: dev
  Branch:
    Type: String
    Description: The branch the stack was deployed.
    Default: master
  ReportBucketName:
    Description: The name of the bucket you have configured to receive CUR files.
    Type: String
  CurPrefix:
    Type: String
    Description: The prefix for the CUR files in the bucket, this should exclude the leading '/'.
  Commit:
    Type: String
  GlueDatabase:
    Type: String
  GlueTable:
    Type: String
  QueryResultsBucketName:
    Type: String


Conditions:
  IsDev: !Equals [!Ref Stage, "dev"]
  IsProd: !Equals [!Ref Stage, "prod"]

Globals:
  Function:
    Runtime: go1.x
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        STAGE: !Ref Stage
        BRANCH: !Ref Branch
        COMMIT: !Ref Commit
        AWS_ACCOUNT_ID: !Ref "AWS::AccountId"
        RAW_EVENT_LOGGING: !If [IsDev, "true", "false"]

Resources:
  PartitionsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PartitionsFunction}"
      RetentionInDays: !If [IsProd, 365, 14]

  PartitionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../dist/handler.zip
      Handler: partitions-curs-lambda
      Environment:
        Variables:
          DATABASE: !Ref GlueDatabase
          TABLE: !Ref GlueTable
          QUERY_BUCKET: !Ref QueryResultsBucketName
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref QueryResultsBucketName
        - S3WritePolicy:
            BucketName: !Ref QueryResultsBucketName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "athena:StartQueryExecution"
                - "athena:GetQueryExecution"
                - "athena:GetQueryResults"
                - "athena:GetWorkGroup"
                - "athena:GetDatabase"
                - "glue:BatchCreatePartition"
                - "glue:GetTable"
                - "glue:GetDatabase"
              Resource: "*"    
      Events:
        S3EventRule:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "aws.s3"
              "detail-type":
                - "Object Created"
              detail:
                bucket:
                  name:
                    - !Ref ReportBucketName
                object:
                  key:
                    - prefix: !Sub "${CurPrefix}/hive"